#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-semantic_version
Version  : 2.9.0
Release  : 52
URL      : https://files.pythonhosted.org/packages/cb/56/4aa487b46d09646eb1863faa7026551d8309ece2281794bf13b20f28ab94/semantic_version-2.9.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/cb/56/4aa487b46d09646eb1863faa7026551d8309ece2281794bf13b20f28ab94/semantic_version-2.9.0.tar.gz
Summary  : A library implementing the 'SemVer' scheme.
Group    : Development/Tools
License  : BSD-2-Clause
Requires: pypi-semantic_version-license = %{version}-%{release}
Requires: pypi-semantic_version-python = %{version}-%{release}
Requires: pypi-semantic_version-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(py)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
Introduction
============
This small python library provides a few tools to handle `SemVer`_ in Python.
It follows strictly the 2.0.0 version of the SemVer scheme.

%package license
Summary: license components for the pypi-semantic_version package.
Group: Default

%description license
license components for the pypi-semantic_version package.


%package python
Summary: python components for the pypi-semantic_version package.
Group: Default
Requires: pypi-semantic_version-python3 = %{version}-%{release}

%description python
python components for the pypi-semantic_version package.


%package python3
Summary: python3 components for the pypi-semantic_version package.
Group: Default
Requires: python3-core
Provides: pypi(semantic_version)

%description python3
python3 components for the pypi-semantic_version package.


%prep
%setup -q -n semantic_version-2.9.0
cd %{_builddir}/semantic_version-2.9.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1644250680
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-semantic_version
cp %{_builddir}/semantic_version-2.9.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-semantic_version/a70ef24806317169e4539b723cad891e08cf1783
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-semantic_version/a70ef24806317169e4539b723cad891e08cf1783

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
